services:
  m3usort:
    image: incmve/m3usort:latest
    container_name: m3usort
    volumes:
      - /opt/stacks/m3usort:/data/M3Usort
      - /data/media/movies:/data/media/movies
      - /data/media/tv:/data/media/tv
    restart: always
    environment:
      - PUID=${PUID:-0}
      - PGID=${PGID:-0}
      - HOST_IP=${HOST_IP}
      - TZ=${TZ}
      - SECRET_KEY=${SECRET_KEY:-ChangeMe!}
    ports:
      - 5050:5050
networks: {}
