from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, SelectField
from wtforms.validators import DataRequired, URL, NumberRange, Optional

class ConfigForm(FlaskForm):
    url = StringField('M3U URL', validators=[DataRequired(), URL()])
    output = StringField('Output File Name', validators=[DataRequired()])
    maxage = IntegerField('Max Age Before Download (hours)', validators=[DataRequired(), NumberRange(min=1, max=24)])
    new_group_title = StringField('Custom Group Title')
    movies_dir = StringField('Movies Directory')
    series_dir = StringField('Series Directory')
    scan_interval = IntegerField('VOD Schedule Interval (hours)', validators=[DataRequired(), NumberRange(min=1, max=24)])
    enable_scheduler = SelectField('Enable VOD scheduler', choices=[('1', 'Yes'), ('0', 'No')], validators=[DataRequired()])
    overwrite_series = SelectField('Overwrite existing episodes', choices=[('1', 'Yes'), ('0', 'No')], validators=[DataRequired()])
    overwrite_movies = SelectField ('Overwrite existing movies', choices=[('1', 'Yes'), ('0', 'No')], validators=[DataRequired()])
    hide_webserver_logs = SelectField('Hide webserver logs', choices=[('1', 'Yes'), ('0', 'No')], validators=[DataRequired()])
    match_type = SelectField('Matching method', choices=[('1', 'String comparison'), ('2', 'Fuzzywuzzy')], validators=[DataRequired()])
    jellyfin_enabled = SelectField('Enable Jellyfin refresh', choices=[('1', 'Yes'), ('0', 'No')], validators=[DataRequired()])
    jellyfin_url = StringField('Jellyfin URL', validators=[Optional()])
    jellyfin_api_key = StringField('Jellyfin API Key', validators=[Optional()])
    tmdb_api_key = StringField('TMDB API Key', validators=[Optional()])
    smb_enabled = SelectField('Enable SMB backup', choices=[('1', 'Yes'), ('0', 'No')], validators=[DataRequired()])
    smb_host = StringField('SMB Host', validators=[Optional()])
    smb_share = StringField('SMB Share', validators=[Optional()])
    smb_path = StringField('SMB Path (optional)', validators=[Optional()])
    smb_username = StringField('SMB Username', validators=[Optional()])
    smb_password = StringField('SMB Password', validators=[Optional()])
    backup_scheduled = SelectField('Daily scheduled backup', choices=[('1', 'Yes'), ('0', 'No')], validators=[DataRequired()])
    backup_time = StringField('Backup time (HH:MM)', validators=[Optional()])
    backup_keep = IntegerField('Backups to keep', validators=[Optional(), NumberRange(min=1, max=99)])
    debug = SelectField('Debug mode', choices=[('no', 'No'), ('yes', 'Yes')], validators=[DataRequired()])
    submit = SubmitField('Save')
